from __future__ import annotations

from pathlib import Path
from threading import Event
from typing import Callable, Protocol, Sequence

from .models import DownloadJob, LibraryFolder, LibraryTrack, Progress, SearchResult, Settings


ProgressCallback = Callable[[Progress], None]


class MediaProvider(Protocol):
    def search(self, query: str, limit: int) -> list[SearchResult]: ...
    def resolve(self, video_id: str) -> SearchResult: ...
    def download(
        self, job: DownloadJob, progress: ProgressCallback, stop_event: Event
    ) -> Path: ...


class JobRepositoryPort(Protocol):
    def add(self, job: DownloadJob) -> DownloadJob: ...
    def get(self, job_id: str) -> DownloadJob | None: ...
    def list(self) -> list[DownloadJob]: ...
    def update(self, job: DownloadJob) -> DownloadJob: ...
    def delete(self, job_id: str) -> None: ...
    def recover_interrupted(self) -> int: ...


class LibraryRepositoryPort(Protocol):
    def add(self, track: LibraryTrack) -> LibraryTrack: ...
    def get(self, track_id: str) -> LibraryTrack | None: ...
    def list(self, filter_text: str, limit: int, offset: int, folder_id: str | None = None) -> tuple[list[LibraryTrack], int]: ...
    def remove(self, track_id: str) -> None: ...
    def list_folders(self) -> list[LibraryFolder]: ...
    def get_folder(self, folder_id: str) -> LibraryFolder | None: ...
    def create_folder(self, name: str) -> LibraryFolder: ...
    def rename_folder(self, folder_id: str, name: str) -> LibraryFolder: ...
    def delete_folder(self, folder_id: str) -> None: ...
    def assign_folder(self, track_id: str, folder_id: str | None) -> None: ...


class SettingsRepositoryPort(Protocol):
    def get(self) -> Settings: ...
    def update(self, settings: Settings) -> Settings: ...


class HistoryRepositoryPort(Protocol):
    def add(self, job_id: str | None, video_id: str | None, event_type: str, detail: dict | None = None) -> None: ...
